### ISSUE TITLE
Does not show over modal.

### ISSUE THREAD

**Issue by xtealer** [jeanverster/react-native-styled-toast#21]
The popup does not show over modal, the modal itself has more priority as I have observed.

**Comment by jeanverster** [comment]
Hi @xtealer, unfortunately because this package is a pure JS solution it won't be possible to display the toast notification above the `Modal` component. Reason being is that the `Modal` component that ships with react-native is a native view which gets rendered on top of the rest of your application, so all regular components will be rendered beneath the modal.

**Comment by xtealer** [comment]
I have noticed with other libraries, but wans't sure of the cause, I wonder if it's possible to emulate a modal with Animation API just using zIndex

**Comment by a-eid** [comment]
@xtealer it's not possible unless you are using something like `wix/react-native-navigation` then it would be possible with their overlay.
